### ISSUE TITLE
User của phần mềm

### ISSUE THREAD

**Issue by giahuy08** [giahuy08/ProjectSE#13]

**Comment by thienviva** [comment]
Các chức năng của User:
1.Đăng ký và đăng nhập/ đăng xuất tài khoản
2.Chọn chức năng (Học từ vựng, Tra từ,...)
3.Học từ vựng
4.Tra từ điển và tự động lưu các từ đã tra
5.Học ngữ pháp (Sắp xếp câu, điền khuyết từ,...)
6.Tải/ mua các tài liệu học ngôn ngữ
7.Luyện nghe
