### ISSUE TITLE
Yêu cầu chức năng

### ISSUE THREAD

**Issue by giahuy08** [giahuy08/ProjectSE#14]

**Comment by thienviva** [comment]
Các yêu cầu chức nặng:
1.Đăng ký và đăng nhập/ đăng xuất tài khoản
2.Học từ vựng
3.Tra từ điển (lưu từ đã tra và hiển thị các từ đồng nghĩa)
4.Học ngữ pháp( Sắp xếp câu, điền khuyết từ,...)
5.Tải và mua tài liệu
6.Luyện nghe
