### ISSUE TITLE
Yêu cầu phi chức năng

### ISSUE THREAD

**Issue by giahuy08** [giahuy08/ProjectSE#15]

**Comment by giahuy08** [comment]
fgasfgasfjagsjdafj

**Comment by thienviva** [comment]
Đưa ra các yêu cầu phi chức năng

**Comment by giahuy08** [comment]
- Không để lộ thông tin người dùng
- Hệ thống có chức năng bảo mật và phân quyền.
-  Người sử dụng chương trình: được cấp username và password và được phân quyền sử dụng chương trình, giúp người quản lý có thể theo dõi, kiểm soát được chương trình, tránh các hợp sửa đổi thông tin không thuộc phạm vi quyền hạn
- Password của người sử dụng được mã hóa trước khi ghi vào dữ liệu và người sử dụng có thể đổi password của mình

**Comment by thienviva** [comment]
•	Hệ thống phải liên tục cập nhật thông tin về các khóa học mới phù hợp với thời đại và những từ người bản địa thường sử dụng.
•	Băng thông mạng đủ (Sufficient network bandwidth)
•	Hiệu quả (tiêu thụ tài nguyên cho tải nhất định) 
•	Tính linh hoạt
•	Khả năng tương tác
•	Các vấn đề pháp lý và cấp phép
•	Khả năng bảo trì
•	Khả năng hoạt động
•	Hiệu suất / thời gian phản hồi (kỹ thuật hiệu suất)
•	Khả năng tương thích nền tảng
•	Quyền riêng tư (tuân thủ luật bảo mật)
•	Tính tiện lợi
•	Thời gian đáp ứng
•	Khả năng tương thích
•	Âm lượng
