### ISSUE TITLE
Hoàn thành tài liệu SRS (usecase, scenario, sequence diagram, UI) #ver_1

### ISSUE THREAD

**Issue by htnquynh** [giahuy08/ProjectSE#30]
- Hoàn thành usecase tổng quát
- Hoàn thành scenario, sequence diagram, UI cho các chức năng: Đăng nhập, Đăng kí, Xem topic và các từ trong topic

**Comment by giahuy08** [comment]
[SRS.pdf](https://github.com/giahuy08/ProjectSE/files/6352020/SRS.pdf)
