### ISSUE TITLE
Hoàn thành tài liệu SRS #ver_2

### ISSUE THREAD

**Issue by htnquynh** [giahuy08/ProjectSE#43]

**Comment by giahuy08** [comment]
SRS Version 2
[SRS-.ver2.pdf](https://github.com/giahuy08/ProjectSE/files/6481799/SRS-.ver2.pdf)

**Comment by giahuy08** [comment]
SRS Version 2
[SRS-ver2.pdf](https://github.com/giahuy08/ProjectSE/files/6481801/SRS-ver2.pdf)
